# Generated by Django 5.2.13 on 2026-04-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("session_type", models.CharField(choices=[("regular", "Regular"), ("extra", "Extra")], default="regular", max_length=10)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="scheduled", max_length=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="class_sessions", to="academics.course"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "faculty"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_class_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "faculty"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["date", "start_time"], "unique_together": {("course", "date", "start_time")}},
        ),
    ]
