# Generated by Django 5.2.13 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendanceqrsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceqrsession",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
