# Generated by Django 5.2.13 on 2026-04-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_classsession"),
        ("attendance", "0003_attendanceqrsession_finalized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="class_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="academics.classsession",
            ),
        ),
        migrations.AddField(
            model_name="attendanceqrsession",
            name="class_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_qr_sessions",
                to="academics.classsession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("class_session__isnull", True)),
                fields=("course", "student", "date"),
                name="uniq_attendance_course_student_date_no_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("class_session__isnull", False)),
                fields=("class_session", "student"),
                name="uniq_attendance_class_session_student",
            ),
        ),
    ]
