# Generated by Django 5.2.13 on 2026-04-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_map_attendance_to_class_session"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="uniq_attendance_course_student_date_no_session",
        ),
        migrations.RemoveConstraint(
            model_name="attendancerecord",
            name="uniq_attendance_class_session_student",
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("class_session", "student")},
        ),
    ]
