# Generated by Django 5.2.13 on 2026-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_mariadb_unique_compat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'course_id', 'class_session_id', 'student_id']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
    ]
