# Generated by Django 5.2.13 on 2026-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceqrsession',
            name='faculty_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceqrsession',
            name='faculty_location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceqrsession',
            name='faculty_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
